apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: snapshot-winservrdesktop
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage:  
