"""
Django settings for admin_custom project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$vcb)2ex^n*2em%6t!ck7a3!0p%=+^fb9w84m@8$jh-eg2(u(h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    'admin_custom',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin_custom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    
    
    },
]

WSGI_APPLICATION = 'admin_custom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
#STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {

    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Welcome !",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Welcome",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Enjoy navigating",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "cni.jpg",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "cni.jpg",

    
}

# settings.py

import stripe

# Set the Stripe API key
stripe.api_key = "sk_test_51MeMiQHmsJXykv8f973lWHHgY37Cx2q3chulZEmC0OTi3oDMXO4kJT9EtQ00VoNfWbybNZVnvKRhGt7IpohjNpgi00t650k46e"
STRIPE_TEST_PUBLISHABLE_KEY='pk_test_51MeMiQHmsJXykv8fgPABCTqyvBVuoyG6GPb96Qmy8ye4R95u9zOCpiDmd3XTT2dxLQVB9VJgr3R7lmr1CH6EqvW000Q0M799z0'
STRIPE_TEST_SECRET_KEY='sk_test_51MeMiQHmsJXykv8f973lWHHgY37Cx2q3chulZEmC0OTi3oDMXO4kJT9EtQ00VoNfWbybNZVnvKRhGt7IpohjNpgi00t650k46e'

STRIPE_PUBLISHABLE_KEY = 'pk_test_51MeMiQHmsJXykv8fgPABCTqyvBVuoyG6GPb96Qmy8ye4R95u9zOCpiDmd3XTT2dxLQVB9VJgr3R7lmr1CH6EqvW000Q0M799z0'
STRIPE_SECRET_KEY = 'sk_test_51MeMiQHmsJXykv8f973lWHHgY37Cx2q3chulZEmC0OTi3oDMXO4kJT9EtQ00VoNfWbybNZVnvKRhGt7IpohjNpgi00t650k46e'
